name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Pylint Black Flake8 Isort
      run: |
        python -m pip install --upgrade pip
        pip install pylint black isort
    - name: Linting with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under 5
    - name: Formatting checks
      run: |
        python -m isort --profile black --check application
        python -m black --check application
